# Experiment settings

# Experiment repository
experiment_repo: "demo-experiment"  # github repo name
organisation: "techtile-by-dramco"  # github org

# Server settings
server:
  host: "techtile-geof.local"
  messaging_port: 5678
  sync_port: 5679
heartbeat_interval: 10

# List of tiles or groups to run general management scripts on.
#tiles: "segmentB segmentF"
tiles: "ceiling walls"                   # group name, single tile, or space-separated list
#tiles: "segmentA"    # group name, single tile, or space-separated list

extra_packages:                     # list of extra packages to be installed on the tiles' rpi's
  - python3-numpy
  - python3-scipy
  - python3-zmq

# Name of the script to run on the clients (make sure it is in the <your-repo>/client folder)
# 1) This is soon to be deprecated
client_script_name: "client-testing.py"
client_script_args:
  - "--config-file"
  - "/home/pi/demo-experiment/experiment-settings.yaml" 
# 2) Use this instead
client_scripts:
  - name: "testscript1.py"
    args:
      - "16"
      - "500"
      - "--delay"
      - "0.2"
    tiles: "segmentA segmentC segmentE segmentG"
  - name: "testscript2.py"
    args:
      - "26"
      - "200"
      - "--delay"
      - "0.5"
    tiles: "segmentB segmentD segmentF"

# Server script behaviour
test_connectivity: True             # set True if you want to test tile connectivity before continuing.
halt_on_connectivity_failure: False  # set False if you want to continue with only the active tiles
